#!/usr/bin/env python
# encoding: utf-8
'''
 -- shortdesc

 is a description

It defines classes_and_methods

@author:     Yuan Luo

@copyright:  2014 Indiana University. All rights reserved.

@license:    Apache License 2.0

@contact:    yuanluo@indiana.edu
@deffield    updated: Updated
'''

import sys
import os
import json
import subprocess
import condor_module
from optparse import OptionParser
#from argparse import ArgumentParser
__all__ = []
__version__ = 0.1
__date__ = '2014-03-01'
__updated__ = '2014-03-14'

RUN = 1
DEBUG = 0
TESTRUN = 0
PROFILE = 0



def main(argv=None):
    '''Command line options.'''

    program_name = os.path.basename(sys.argv[0])
    program_version = "v0.1"
    program_build_date = "%s" % __updated__

    program_version_string = '%%prog %s (%s)' % (program_version, program_build_date)
    #program_usage = '''usage: spam two eggs''' # optional - will be autogenerated by optparse
    program_longdesc = '''''' # optional - give further explanation about what the program does
    program_license = "Copyright 2014 Yuan Luo (Indiana University)                                            \
                Licensed under the Apache License 2.0\nhttp://www.apache.org/licenses/LICENSE-2.0"

    if argv is None:
        argv = sys.argv[1:]
    try:
      # setup option parser
        parser = OptionParser(version=program_version_string, epilog=program_longdesc, description=program_license)
        parser.disable_interspersed_args()
        parser.add_option("-i", "--in", dest="infile", help="set input path [default: %default]", metavar="FILE")
        parser.add_option("-o", "--out", dest="outfile", help="set output path [default: %default]", metavar="FILE")
        
        parser.add_option("-f", "--format", dest="format", help="Output Format: json, text")
        parser.add_option("-v", "--verbose", dest="verbose", action="count", help="set verbosity level [default: %default]")
        
        # set defaults
        parser.set_defaults(outfile="./out.txt", infile="./in.txt", format="text")

        # process options
        (opts, args) = parser.parse_args(argv)
        if opts.verbose > 0:
            print("verbosity level = %d" % opts.verbose)
        if opts.infile:
            print("infile = %s" % opts.infile)
        if opts.outfile:
            print("outfile = %s" % opts.outfile)
        if opts.format:
            print("json = %s" % opts.format)
        
        for a in args:
            print a
        
        # MAIN BODY #
        condor_module.condorCLI(args,opts.format)
        
    except Exception, e:
        indent = len(program_name) * " "
        sys.stderr.write(program_name + ": " + repr(e) + "\n")
        sys.stderr.write(indent + "  for help use --help")
        return 2


if __name__ == "__main__":
    if RUN:
        condor_module.printTest("RUN")
    if DEBUG:
        sys.argv.append("-h")
    if TESTRUN:
        import doctest
        doctest.testmod()
    if PROFILE:
        import cProfile
        import pstats
        profile_filename = '_profile.txt'
        cProfile.run('main()', profile_filename)
        statsfile = open("profile_stats.txt", "wb")
        p = pstats.Stats(profile_filename, stream=statsfile)
        stats = p.strip_dirs().sort_stats('cumulative')
        stats.print_stats()
        statsfile.close()
        sys.exit(0)
    sys.exit(main())